version: "3.1"

volumes:
  pg_text:

services:
  text_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = 12345
      - POSTGRES_DB = text_db
    volumes:
      - pg_text:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - text_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://text_db:5432/text_db'
      JAVA_OPTS: '-Xmx512'
